version: "3.3"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=personal-data
    restart: always

  fastify-backend:
    build: ./parser-backend
    container_name: fastify-backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MONGO_CON_STRING=mongodb://mongo_db:${MONGO_PORT:-27017}/personal-data
      - PORT=${BACKEND_PORT:-3033}
    depends_on: 
      - mongo_db
    restart: always

  react-frontend:
    build:
      context: ./data-vizualizer
      args:
        - VITE_PORT=${FRONTEND_PORT:-3034}
        - VITE_BACKEND_URL=http://127.0.0.1:${BACKEND_PORT:-3033}
        - VITE_BACKEND_WS=ws://127.0.0.1:${BACKEND_PORT:-3033}/ws
        - VITE_PROXY=${VITE_PROXY}
    container_name: react-frontend
    ports:
      - "${FRONTEND_PORT:-3034}:${FRONTEND_PORT:-3034}"
    depends_on:
      - fastify-backend
      - mongo_db
    restart: always
